//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SliceCalendarAgent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string txn_status { get; set; }
        public string txn_id { get; set; }
        public string txn_type { get; set; }
        public string custom { get; set; }
        public string test_ipn { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string contact_phone { get; set; }
        public string address_street { get; set; }
        public string address_city { get; set; }
        public string address_state { get; set; }
        public string address_zip { get; set; }
        public string verify_sign { get; set; }
        public string address_name { get; set; }
        public string payer_business_name { get; set; }
        public string payer_email { get; set; }
        public string payer_id { get; set; }
        public string auth_amount { get; set; }
        public string auth_exp { get; set; }
        public string auth_status { get; set; }
        public string fraud_managment_pending_filters_x { get; set; }
        public string item_namex { get; set; }
        public string item_numberx { get; set; }
        public string mc_fee { get; set; }
        public string mc_gross { get; set; }
        public string memo { get; set; }
        public string num_cart_items { get; set; }
        public string option_name1 { get; set; }
        public string option_name2 { get; set; }
        public string option_selection1_1 { get; set; }
        public string option_selection2_1 { get; set; }
        public string payer_status { get; set; }
        public string payment_date { get; set; }
        public string payment_status { get; set; }
        public string payment_type { get; set; }
        public string quantity { get; set; }
        public string reason_code { get; set; }
        public string transaction_entity { get; set; }
        public string option_selection1_2 { get; set; }
        public string option_selection1_3 { get; set; }
        public string option_selection1_4 { get; set; }
        public string option_selection1_5 { get; set; }
        public string option_selection2_2 { get; set; }
        public string option_selection2_3 { get; set; }
        public string option_selection2_4 { get; set; }
        public string option_selection2_5 { get; set; }
        public string option_selection1_6 { get; set; }
        public string option_selection1_7 { get; set; }
        public string option_selection1_8 { get; set; }
        public string option_selection1_9 { get; set; }
        public string option_selection1_10 { get; set; }
        public string option_selection2_6 { get; set; }
        public string option_selection2_7 { get; set; }
        public string option_selection2_8 { get; set; }
        public string option_selection2_9 { get; set; }
        public string option_selection2_10 { get; set; }
    }
}
